### ISSUE TITLE
showmeboone.com is frequently inaccessible. 

### ISSUE THREAD

**Issue by digen** [palewire/first-web-scraper#2]
I would suggest a different website/URL for demonstrating web scraping. Possibly, will write one by this weekend where the website is hosted on one of my server allowing for web scraping without breaking any laws/Terms of use.

**Comment by andylolz** [comment]
> showmeboone.com is frequently inaccessible

Can I suggest self-hosting the example – e.g. in this repo (and using rawgit.com to serve it).

**Comment by palewire** [comment]
This is now a different URL
